plugins {
    alias libs.plugins.android.library
}

android {
    namespace = 'com.chatwaifu.live2d'
    compileSdk libs.versions.compileSdk.get().toInteger()

    defaultConfig {
        minSdk libs.versions.minSdk.get().toInteger()

        consumerProguardFiles "consumer-rules.pro"
        ndk{
            abiFilters 'armeabi-v7a', 'arm64-v8a'
        }
        externalNativeBuild {
            cmake {
                cppFlags '-std=c++11'
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    externalNativeBuild {
        cmake {
            path "CMakeLists.txt"
            version = libs.versions.cmake.get()
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.toVersion(libs.versions.jvmTarget.get())
        targetCompatibility JavaVersion.toVersion(libs.versions.jvmTarget.get())
    }
    lint {
        targetSdk libs.versions.targetSdk.get().toInteger()
    }
    testOptions {
        targetSdk libs.versions.targetSdk.get().toInteger()
    }
}

dependencies {
    implementation libs.androidx.core.ktx
}
