plugins {
    alias libs.plugins.android.library
    alias libs.plugins.kotlin.android
}

android {
    namespace 'com.k2fsa.sherpa.ncnn'
    compileSdk libs.versions.compileSdk.get().toInteger()

    defaultConfig {
        minSdk libs.versions.minSdk.get().toInteger()
        consumerProguardFiles "consumer-rules.pro"
        ndk {
            abiFilters "armeabi-v7a","arm64-v8a"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.toVersion(libs.versions.jvmTarget.get())
        targetCompatibility JavaVersion.toVersion(libs.versions.jvmTarget.get())
    }
    kotlinOptions {
        jvmTarget = libs.versions.jvmTarget.get()
    }
    buildFeatures {
        aidl true
    }
    sourceSets {
        main {
            jniLibs.srcDirs=['src/main/jniLibs']
        }
    }
    lint {
        targetSdk libs.versions.targetSdk.get().toInteger()
    }
    testOptions {
        targetSdk libs.versions.targetSdk.get().toInteger()
    }
}

dependencies {
    implementation libs.androidx.core.ktx
    implementation libs.androidx.lifecycle.livedata.ktx
    implementation libs.androidx.lifecycle.viewmodel.ktx
}
