plugins {
    alias libs.plugins.android.library
}

android {
    namespace = 'com.chatwaifu.vits'
    compileSdk libs.versions.compileSdk.get().toInteger()

    defaultConfig {
        minSdk libs.versions.minSdk.get().toInteger()

        externalNativeBuild {
            cmake {
                cppFlags '-std=c++11'
            }
        }
        ndk{
            abiFilters 'armeabi-v7a', 'arm64-v8a'
        }
    }

    externalNativeBuild {
        cmake {
            path file('src/main/cpp/CMakeLists.txt')
            version = libs.versions.cmake.get()
        }
    }
    buildFeatures {
        viewBinding = true
    }
    compileOptions {
        sourceCompatibility JavaVersion.toVersion(libs.versions.jvmTarget.get())
        targetCompatibility JavaVersion.toVersion(libs.versions.jvmTarget.get())
    }
    lint {
        targetSdk libs.versions.targetSdk.get().toInteger()
    }
    testOptions {
        targetSdk libs.versions.targetSdk.get().toInteger()
    }

}

dependencies {
    implementation libs.androidx.core.ktx
    implementation libs.androidx.appcompat
    implementation libs.material
    implementation libs.androidx.constraintlayout
    implementation libs.gson
    implementation libs.androidx.navigation.fragment
    implementation libs.androidx.navigation.ui.ktx
    implementation libs.pinyin4j
    implementation libs.pinyin.houbb
}
